#ifndef _LINUX_TCHIP_SYSINF_H
#define _LINUX_TCHIP_SYSINF_H

typedef enum
{
	// USB vendor and product
	TSCI_USB_VENDOR = 12,
	TSCI_USB_PRODUCT = 20,
	// 版本信息 32:100
	TSCI_TCHIP_VERSION = 32,

	// 硬件开关标志 132:8
	TCSI_CAMERA_ONOFF = 132,
	TCSI_HDMI_ONOFF,
	TCSI_PIN_BASE_LOW = 135,
	TCSI_PIN_BASE_HIGH,
	TCSI_CAMERA_FRONT_POWERDOWN_PIN = 137,
	TCSI_CAMERA_BACK_POWERDOWN_PIN,
	TCSI_GPS_ONOFF,

	// 调屏信息 140:36
	TCSI_SCREEN_INFO = 140,
	TCSI_SCREEN_FACE = TCSI_SCREEN_INFO + 0,
	TCSI_SCREEN_PIX_CLK = TCSI_SCREEN_INFO + 1,
	TCSI_SCREEN_LCDC_ACLK = TCSI_SCREEN_INFO + 5,
	TCSI_SCREEN_HSYNC_LEN = TCSI_SCREEN_INFO + 9,
	TCSI_SCREEN_LEFT_MARGIN = TCSI_SCREEN_INFO + 11,
	TCSI_SCREEN_XRES = TCSI_SCREEN_INFO + 13,
	TCSI_SCREEN_RIGHT_MARGIN = TCSI_SCREEN_INFO + 15,
	TCSI_SCREEN_VSYNC_LEN = TCSI_SCREEN_INFO + 17,
	TCSI_SCREEN_UPPER_MARGIN = TCSI_SCREEN_INFO + 19,
	TCSI_SCREEN_YRES = TCSI_SCREEN_INFO + 21,
	TCSI_SCREEN_LOWER_MARGIN = TCSI_SCREEN_INFO + 23,
	TCSI_SCREEN_WIDTH = TCSI_SCREEN_INFO + 25,
	TCSI_SCREEN_HEIGHT = TCSI_SCREEN_INFO + 27,
	TCSI_SCREEN_PIN_CLK = TCSI_SCREEN_INFO + 29,
	TCSI_SCREEN_SWAP_RB = TCSI_SCREEN_INFO + 30,

	// 电容屏信息 176:108
	TCSI_TOUCH_CONFIG = 176,
	// 电池容量信息 284:48
	TCSI_ADC_BATTERY_TABLE = 284,
	TCSI_ADC_AC_TABLE = 308,

	// camera
	TCSI_CAMERA_PRESTART = 340 - 1,
#ifdef	CONFIG_SOC_CAMERA_GT2005
	TCSI_CAMERA_GT2005,
#endif
#ifdef	CONFIG_SOC_CAMERA_GC0308
	TCSI_CAMERA_GC0308,
#endif
#ifdef	CONFIG_SOC_CAMERA_HI704
	TCSI_CAMERA_HI704,
#endif
#ifdef	CONFIG_SOC_CAMERA_HI253
	TCSI_CAMERA_HI253,
#endif
#ifdef	CONFIG_SOC_CAMERA_GC0307
	TCSI_CAMERA_GC0307,
#endif
#ifdef	CONFIG_SOC_CAMERA_MT9M111
	TCSI_CAMERA_MT9M111,
#endif
#ifdef	CONFIG_SOC_CAMERA_MT9M112
	TCSI_CAMERA_MT9M112,
#endif
#ifdef	CONFIG_SOC_CAMERA_MT9T031
	TCSI_CAMERA_MT9T031,
#endif
#ifdef	CONFIG_SOC_CAMERA_MT9P111
	TCSI_CAMERA_MT9P111,
#endif
#ifdef	CONFIG_SOC_CAMERA_MT9D112
	TCSI_CAMERA_MT9D112,
#endif
#ifdef CONFIG_SOC_CAMERA_OV5640
    TCSI_CAMERA_OV5640,
#endif
#ifdef CONFIG_SOC_CAMERA_OV2640_RK
    TCSI_CAMERA_OV2640,
#endif
#ifdef CONFIG_SOC_CAMERA_OV2659
    TCSI_CAMERA_OV2659_F,	// front
    TCSI_CAMERA_OV2659_B,	// back
#endif
#ifdef CONFIG_SOC_CAMERA_SP2518
    TCSI_CAMERA_SP2518_F,      // front
    TCSI_CAMERA_SP2518_B,      // back
#endif
	TCSI_CAMERA_END,

	// hdmi
	TCSI_HDMI_PRESTART = 440 -1,
#if	CONFIG_ANX7150 || CONFIG_ANX7150_NEW
	TCSI_HDMI_ANX7150,
#endif
#if	CONFIG_CAT6611 || CONFIG_CAT6611_NEW
	TCSI_HDMI_CAT6611,
#endif
#if    defined(CONFIG_HDMI_RK30)
    TCSI_HDMI_RK30,
#endif
#if defined(CONFIG_HDMI_RK610)
	TCSI_HDMI_RK610,
#endif
	TCSI_HDMI_END,

	// wifi
	TCSI_WIFI_PRESTART = 540 - 1,
#ifdef	CONFIG_AR6003
	TCSI_WIFI_AR6003,
#endif
#ifdef	CONFIG_BCM4329
	TCSI_WIFI_BCM4329,
#endif
#ifdef	CONFIG_MV8686
	TCSI_WIFI_MV8686,
#endif
#ifdef	CONFIG_RTL8192CU
	TCSI_WIFI_RTL8192,
#endif
#ifdef CONFIG_RK903
	TCSI_WIFI_RK903,
#endif
#ifdef CONFIG_RT5370V2_STA
	TCSI_WIFI_RT5370,
#endif
#ifdef CONFIG_RT5370
	TCSI_WIFI_RT5370V2,
#endif
#ifdef CONFIG_MT7601
    TCSI_WIFI_MT7601,
#endif
	
	TCSI_WIFI_END,

	// codec
	TCSI_CODEC_PRESTART = 640 - 1,
#ifdef	CONFIG_SND_RK29_SOC_WM8988
	TCSI_CODEC_WM8988,
#endif
#ifdef	CONFIG_SND_RK29_SOC_WM8900
	TCSI_CODEC_WM8900,
#endif
#ifdef	CONFIG_SND_RK29_SOC_RT5621
	TCSI_CODEC_RT5621,
#endif
#ifdef	CONFIG_SND_RK29_SOC_WM8994
	TCSI_CODEC_WM8994,
#endif
#ifdef	CONFIG_SND_RK29_SOC_RT5631
	TCSI_CODEC_RT5631,
#endif
#ifdef	CONFIG_SND_RK29_SOC_RK610
	TCSI_CODEC_RK610,
#endif
#ifdef  CONFIG_SND_RK29_SOC_ES8323
    TCSI_CODEC_ES8323,
#endif
	TCSI_CODEC_END,

	// modem
	TCSI_MODEM_PRESTART = 740 - 1,
#ifdef CONFIG_MODEM_ROCKCHIP_DEMO
	TCSI_MODEM_OTHERS,
#endif
#ifdef	CONFIG_TDM330
	TCSI_MODEM_TDM330,
#endif
	TCSI_MODEM_END,
}TCSI_POS;

extern unsigned char TCHIPSYSINFO[];

#define tcsi_get_pointer(pos)	(&TCHIPSYSINFO[pos])
#define tcsi_get_value(pos)		(TCHIPSYSINFO[pos])

// 工具暂时只支持前后两个摄像头的配置
#define TCSI_SENSOR_POS_NONE        0
#define TCSI_SENSOR_POS_FRONT       1
#define TCSI_SENSOR_POS_BACK        2

#define TCSI_GET_SENSOR_INDEX(x) ((x) - TCSI_CAMERA_PRESTART - 1)

#endif	/* _LINUX_TCHIP_SYSINF_H */
